apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toofics-poi-backend-app-dev
  annotations:
    argocd/app-name: toofics-poi-backend-app-dev
    backstage.io/kubernetes-id: toofics-poi-backend-app
    backstage.io/kubernetes-namespace: toofics
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-vegas/toofics-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/dev-pipelines/ns/toofics/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/k8s/ns/toofics/deployments/toofics-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/#https://github.com/rhdh-vegas/toofics-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/toofics"
  system: workshop-system-toofics
  providesApis:
    - backend-api-toofics
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-toofics
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/toofics"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-toofics
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://toofics-poi-backend-app-toofics.apps.rosa-bvg5j.wov7.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-vegas/toofics-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/toofics"
  system: workshop-system-toofics
  definition:
    $text: https://github.com/rhdh-vegas/toofics-backend/tree/main/src/main/resources/META-INF/openapi.yaml
